import Head from 'next/head'

const Header = ({titleSite, desc}) => {
    return(
        <div>
            <Head>
                <title>{titleSite || "Create Next App"}</title>
                <meta name="description" content={desc || "Generated by create next app"} />
                <link rel="icon" href="/favicon.ico" />
                <link rel="preconnect" href="https://fonts.googleapis.com"/>
                <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin/>
                <link href="https://fonts.googleapis.com/css2?family=Bagel+Fat+One&display=swap" rel="stylesheet"/>
            </Head>
            <header>
                <h1><a href="/">Hero industrial</a></h1>
            </header>
        </div>
    )
}

export default Header